name: clean_pill_navbar_example
description: "Example app for clean_pill_navbar."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  clean_pill_navbar:
    path: ../
  material_ui: ^1.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true